services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - db_data:/var/lib/postgresql

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      JWT_ACCESS_SECRET_FILE: /run/secrets/jwt_access_secret
      JWT_REFRESH_SECRET_FILE: /run/secrets/jwt_refresh_secret
      DOCUMENTS_DIR: /app/documents
    secrets:
      - postgres_password
      - jwt_access_secret
      - jwt_refresh_secret
    volumes:
      - backend_documents:/app/documents

  llama_embedding:
    image: ghcr.io/ggml-org/llama.cpp:server
    ports:
      - "8080:8080"
    command:
      - "--embeddings"
      - "--hf-repo"
      - "enacimie/Qwen3-Embedding-0.6B-Q4_K_M-GGUF"
      - "--hf-file"
      - "qwen3-embedding-0.6b-q4_k_m.gguf"
      - "-c"
      - "2048"

volumes:
  db_data:
  backend_documents:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  jwt_access_secret:
    file: ./secrets/jwt_access_secret.txt
  jwt_refresh_secret:
    file: ./secrets/jwt_refresh_secret.txt
